### PR TITLE
fix(cache file, base report): add option expire in to BaseReport and …

### PR DESCRIPTION
**Pull request by flash1nho**
…fix #exists? method in CacheFile and same fixes

### CODE REVIEW

**Comment by flash1nho** [comment]
@artofhuman @sclinede

**Comment by artofhuman** [comment]
ok

**Comment by flash1nho** [comment]
@ZhidkovDenis

**Comment by sclinede** [comment]
wow nice. thnx

**Comment by sclinede** [comment]
OK :+1:

**Comment by ZhidkovDenis** [comment]
:+1: nice

**Pull request merged**
